package com.example.springboot.service;

import com.example.springboot.entity.Volunteer;
import com.example.springboot.entity.VolunteerTraining;
import com.example.springboot.entity.VolunteerTrainingParticipation;
import com.example.springboot.exception.CustomException;
import com.example.springboot.mapper.VolunteerMapper;
import com.example.springboot.mapper.VolunteerTrainingMapper;
import com.example.springboot.mapper.VolunteerTrainingParticipationMapper;
import com.github.pagehelper.PageHelper;
import com.github.pagehelper.PageInfo;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Service
public class VolunteerTrainingService {

    @Resource
    private VolunteerTrainingMapper volunteerTrainingMapper;
    @Resource
    private VolunteerTrainingParticipationMapper participationMapper;

    // Valid training statuses from your table definition
    private static final List<String> VALID_TRAINING_STATUSES = Arrays.asList(
            "待审核", "审核通过", "审核不通过", "进行中", "已结束", "已停用"
    );

    /**
     * 添加新的志愿培训
     *
     * @param volunteerTraining 志愿培训对象
     * @throws CustomException if validation fails
     */
    @Transactional
    public void addTraining(VolunteerTraining volunteerTraining) throws CustomException {
        if (volunteerTraining == null || volunteerTraining.getOrgId() == null) {
            throw new CustomException("组织ID不能为空", "400");
        }
        if (volunteerTraining.getTrainingName() == null || volunteerTraining.getTrainingName().trim().isEmpty()) {
            throw new CustomException("培训名称不能为空", "400");
        }
        if (volunteerTraining.getTheme() == null || volunteerTraining.getTheme().trim().isEmpty()) {
            throw new CustomException("培训主题不能为空", "400");
        }
        if (volunteerTraining.getStartTime() == null || volunteerTraining.getEndTime() == null) {
            throw new CustomException("培训开始和结束时间不能为空", "400");
        }
        if (volunteerTraining.getStartTime().after(volunteerTraining.getEndTime())) {
            throw new CustomException("培训开始时间不能晚于结束时间", "400");
        }
        if (volunteerTraining.getRecruitmentCount() == null || volunteerTraining.getRecruitmentCount() <= 0) {
            throw new CustomException("招募人数必须大于0", "400");
        }
        if (volunteerTraining.getTrainingStatus() == null || !VALID_TRAINING_STATUSES.contains(volunteerTraining.getTrainingStatus())) {
            volunteerTraining.setTrainingStatus("待审核"); // Defaulting
        }
        if (volunteerTraining.getContactPersonPhone() == null || volunteerTraining.getContactPersonPhone().trim().isEmpty()) {
            throw new CustomException("负责人联系方式不能为空", "400");
        }
        // CreationTime defaults to GETDATE() in DB.
        // TrainingID will be auto-generated by database trigger
        volunteerTrainingMapper.insert(volunteerTraining);
    }

    /**
     * 根据培训ID更新志愿培训信息
     *
     * @param volunteerTraining 志愿培训对象
     * @throws CustomException if validation fails or training not found
     */
    @Transactional
    public void updateTraining(VolunteerTraining volunteerTraining) throws CustomException {
        if (volunteerTraining == null || volunteerTraining.getTrainingId() == null) {
            throw new CustomException("培训ID不能为空以进行更新", "400");
        }
        VolunteerTraining existingTraining = volunteerTrainingMapper.selectById(volunteerTraining.getTrainingId());
        if (existingTraining == null) {
            throw new CustomException("未找到要更新的培训，ID: " + volunteerTraining.getTrainingId(), "404");
        }

        if (volunteerTraining.getStartTime() != null && volunteerTraining.getEndTime() != null &&
                volunteerTraining.getStartTime().after(volunteerTraining.getEndTime())) {
            throw new CustomException("培训开始时间不能晚于结束时间", "400");
        }
        if (volunteerTraining.getRecruitmentCount() != null && volunteerTraining.getRecruitmentCount() <= 0) {
            throw new CustomException("招募人数必须大于0", "400");
        }
        if (volunteerTraining.getTrainingStatus() != null && !VALID_TRAINING_STATUSES.contains(volunteerTraining.getTrainingStatus())) {
            throw new CustomException("无效的培训状态: " + volunteerTraining.getTrainingStatus(), "400");
        }

        volunteerTrainingMapper.updateById(volunteerTraining);
    }

    /**
     * 根据培训ID删除志愿培训
     *
     * @param trainingId 培训ID
     * @throws CustomException if validation fails or training not found
     */
    @Transactional
    public void deleteTrainingById(String trainingId) throws CustomException {
        if (trainingId == null || trainingId.trim().isEmpty()) {
            throw new CustomException("培训ID不能为空", "400");
        }
        VolunteerTraining existingTraining = volunteerTrainingMapper.selectById(trainingId);
        if (existingTraining == null) {
            throw new CustomException("未找到要删除的培训，ID: " + trainingId, "404");
        }
        volunteerTrainingMapper.deleteById(trainingId);
    }

    /**
     * 根据培训ID查询志愿培训信息
     *
     * @param trainingId 培训ID
     * @return 志愿培训对象
     * @throws CustomException if validation fails
     */
    public VolunteerTraining getTrainingById(String trainingId) throws CustomException {
        if (trainingId == null || trainingId.trim().isEmpty()) {
            throw new CustomException("培训ID不能为空", "400");
        }
        return volunteerTrainingMapper.selectById(trainingId);
    }

    /**
     * 查询所有志愿培训 (可带条件过滤)
     *
     * @param volunteerTraining 包含过滤条件的志愿培训对象
     * @return 志愿培训列表
     */
    public List<VolunteerTraining> getAllTrainings(VolunteerTraining volunteerTraining) {
        return volunteerTrainingMapper.selectAll(volunteerTraining);
    }

    /**
     * 分页查询志愿培训信息
     *
     * @param volunteerTraining 包含过滤条件的志愿培训对象
     * @param pageNum           页码
     * @param pageSize          每页大小
     * @return 分页后的志愿培训列表
     */
    public PageInfo<VolunteerTraining> getTrainingPage(VolunteerTraining volunteerTraining, Integer pageNum, Integer pageSize) {
        PageHelper.startPage(pageNum, pageSize);
        List<VolunteerTraining> list = volunteerTrainingMapper.selectAll(volunteerTraining);
        return PageInfo.of(list);
    }

    /**
     * 根据组织ID查询培训
     *
     * @param orgId 组织ID
     * @return 志愿培训列表
     * @throws CustomException if validation fails
     */
    public List<VolunteerTraining> getTrainingsByOrgId(String orgId) throws CustomException {
        if (orgId == null || orgId.trim().isEmpty()) {
            throw new CustomException("组织ID不能为空", "400");
        }
        return volunteerTrainingMapper.selectByOrgId(orgId);
    }

    /**
     * 根据培训状态查询培训
     *
     * @param status 培训状态
     * @return 志愿培训列表
     * @throws CustomException if validation fails
     */
    public List<VolunteerTraining> getTrainingsByStatus(String status) throws CustomException {
        if (status == null || status.trim().isEmpty() || !VALID_TRAINING_STATUSES.contains(status)) {
            throw new CustomException("无效或空的培训状态", "400");
        }
        return volunteerTrainingMapper.selectByStatus(status);
    }

    /**
     * 根据培训主题查询培训
     *
     * @param theme 培训主题
     * @return 志愿培训列表
     * @throws CustomException if validation fails
     */
    public List<VolunteerTraining> getTrainingsByTheme(String theme) throws CustomException {
        if (theme == null || theme.trim().isEmpty()) {
            throw new CustomException("培训主题不能为空", "400");
        }
        return volunteerTrainingMapper.selectByTheme(theme);
    }

    /**
     * 审核/更新培训状态
     *
     * @param trainingId      培训ID
     * @param newStatus       新的状态
     * @param reviewerAdminId 审核员ID (可以为null)
     * @throws CustomException if validation fails or training not found
     */
    @Transactional
    public void reviewTraining(String trainingId, String newStatus, String reviewerAdminId) throws CustomException {
        if (trainingId == null || trainingId.trim().isEmpty()) {
            throw new CustomException("培训ID不能为空", "400");
        }
        if (newStatus == null || !VALID_TRAINING_STATUSES.contains(newStatus)) {
            throw new CustomException("无效的培训状态: " + newStatus, "400");
        }
        VolunteerTraining training = volunteerTrainingMapper.selectById(trainingId);
        if (training == null) {
            throw new CustomException("未找到培训: " + trainingId, "404");
        }
        volunteerTrainingMapper.updateTrainingStatus(trainingId, newStatus, reviewerAdminId);
    }

    /**
     * 获取指定志愿者参与的所有培训
     *
     * @param volunteerId 志愿者ID
     * @return 培训列表
     */
    @Transactional(readOnly = true) // <--- 在这里添加注解
    public List<Map<String, Object>> getParticipatedTrainings(String volunteerId) throws CustomException {
        if (volunteerId == null || volunteerId.trim().isEmpty()) {
            throw new CustomException("志愿者ID不能为空", "400");
        }
        return volunteerTrainingMapper.findParticipatedTrainingsByVolunteerId(volunteerId);
    }

     // 【主要修改点】修改了此方法的返回类型和逻辑
    /**
     * 志愿者为培训进行评分，并返回更新后的记录
     *
     * @param volunteerId 志愿者ID
     * @param trainingId  培训ID
     * @param rating      评分 (1-10)
     * @return 更新后的培训记录 (Map)
     */
    @Transactional
    public void rateTraining(String volunteerId, String trainingId, Integer rating) throws CustomException {
        if (volunteerId == null || trainingId == null || rating == null) {
            throw new CustomException("参数不能为空", "400");
        }
        if (rating < 1 || rating > 10) {
            throw new CustomException("评分必须在1-10分之间", "400");
        }

        int updatedRows = participationMapper.updateVolunteerRating(volunteerId, trainingId, rating);

        if (updatedRows == 0) {
            throw new CustomException("评价失败，可能未参与该培训或记录不存在", "404");
        }

        // 直接在同一个事务里，查询并返回最新的数据
        //return volunteerTrainingMapper.findSingleParticipatedTraining(volunteerId, trainingId);
    }
    /**
     * 根据组织ID查询培训，并联表获取组织名称
     * @param orgId 组织ID
     * @return 包含组织名称的培训列表
     * @throws CustomException if validation fails
     */
    public List<VolunteerTraining> getTrainingsWithOrgNameByOrgId(String orgId) throws CustomException{
        if (orgId == null || orgId.trim().isEmpty()) {
            throw new CustomException("组织ID不能为空", "400");
        }
        return volunteerTrainingMapper.selectTrainingsWithOrgNameByOrgId(orgId);
    }

    /**
     * 根据培训状态查询培训，并联表获取组织名称
     * @param status 培训状态
     * @return 包含组织名称的培训列表
     * @throws CustomException if validation fails
     */
    public List<VolunteerTraining> getTrainingsWithOrgNameByStatus(String status) throws CustomException {
        if (status == null || status.trim().isEmpty() || !VALID_TRAINING_STATUSES.contains(status)) {
            throw new CustomException("无效或空的培训状态", "400");
        }
        return volunteerTrainingMapper.selectTrainingsWithOrgNameByStatus(status);
    }

    /**
     * 根据培训主题查询培训，并联表获取组织名称
     * @param theme 培训主题
     * @return 包含组织名称的培训列表
     * @throws CustomException if validation fails
     */
    public List<VolunteerTraining> getTrainingsWithOrgNameByTheme(String theme) throws CustomException{
        if (theme == null || theme.trim().isEmpty()) {
            throw new CustomException("培训主题不能为空", "400");
        }
        return volunteerTrainingMapper.selectTrainingsWithOrgNameByTheme(theme);
    }




   // 在类的顶部注入 VolunteerMapper
    @Resource
    private VolunteerMapper volunteerMapper;





/**
     * 【核心】获取指定培训的参与者列表（包含签到状态）
     * @param trainingId 培训ID
     * @return 包含志愿者完整信息和签到状态的Map列表
     */
    public List<Map<String, Object>> getParticipantsByTrainingId(String trainingId) {
        if (!StringUtils.hasText(trainingId)) {
            throw new CustomException("培训ID不能为空", "400");
        }
        return participationMapper.selectParticipantsWithStatusByTrainingId(trainingId);
    }

    /**
     * 【核心】更新志愿者在某项培训中的签到状态
     */
    @Transactional
    public void updateParticipationStatus(String trainingId, String volunteerId, String isCheckedIn) {
        if (!StringUtils.hasText(trainingId) || !StringUtils.hasText(volunteerId) || !StringUtils.hasText(isCheckedIn)) {
            throw new CustomException("参数不能为空 (trainingId, volunteerId, isCheckedIn)", "400");
        }

        VolunteerTrainingParticipation existingRecord = participationMapper.selectByPrimaryKey(volunteerId, trainingId);
        if (existingRecord == null) {
            throw new CustomException("更新签到状态失败，未找到对应的参与记录", "404");
        }

        VolunteerTrainingParticipation participationToUpdate = new VolunteerTrainingParticipation();
        participationToUpdate.setVolunteerId(volunteerId);
        participationToUpdate.setTrainingId(trainingId);
        participationToUpdate.setIsCheckedIn(isCheckedIn);

        int updatedRows = participationMapper.updateByPrimaryKey(participationToUpdate);

        if (updatedRows == 0) {
            throw new CustomException("数据库更新失败，请稍后重试", "500");
        }
    }

    /**
     * 获取可添加到指定培训的志愿者列表 (排除已参加的)
     */
    public List<Volunteer> getPotentialParticipantsForTraining(String trainingId, String name) {
        List<Volunteer> allVolunteers = volunteerMapper.searchVolunteersByName(name);
        List<String> participantIds = participationMapper.selectByTrainingId(trainingId)
                .stream()
                .map(VolunteerTrainingParticipation::getVolunteerId)
                .collect(Collectors.toList());

        return allVolunteers.stream()
                .filter(v -> !participantIds.contains(v.getVolunteerId()))
                .collect(Collectors.toList());
    }

    /**
     * 将一名志愿者添加到培训中
     */
    @Transactional
    public void enrollVolunteerInTraining(String trainingId, String volunteerId) {
        if (!StringUtils.hasText(trainingId) || !StringUtils.hasText(volunteerId)) {
            throw new CustomException("培训ID和志愿者ID均不能为空", "400");
        }

        VolunteerTrainingParticipation existing = participationMapper.selectByPrimaryKey(volunteerId, trainingId);
        if (existing != null) {
            throw new CustomException("该志愿者已参加此培训，请勿重复添加", "409");
        }

        VolunteerTrainingParticipation newParticipation = new VolunteerTrainingParticipation();
        newParticipation.setTrainingId(trainingId);
        newParticipation.setVolunteerId(volunteerId);
        newParticipation.setIsCheckedIn("否");

        participationMapper.insert(newParticipation);
    }


    /**
     * 【新增】组织对参与培训的志愿者进行评分
     * @param trainingId 培训ID
     * @param volunteerId 志愿者ID
     * @param rating 评分 (1-10)
     * @throws CustomException 业务逻辑异常
     */
    @Transactional
    public void rateParticipantByOrg(String trainingId, String volunteerId, Integer rating) throws CustomException {
        // 1. 验证参数
        if (!StringUtils.hasText(trainingId) || !StringUtils.hasText(volunteerId) || rating == null) {
            throw new CustomException("400", "培训ID、志愿者ID和评分均不能为空");
        }
        if (rating < 1 || rating > 10) {
            throw new CustomException("400", "评分必须在1到10之间");
        }

        // 2. 检查培训状态
        VolunteerTraining training = volunteerTrainingMapper.selectById(trainingId);
        if (training == null) {
            throw new CustomException("404", "未找到ID为 " + trainingId + " 的培训");
        }
        if (!"已结束".equals(training.getTrainingStatus())) {
            throw new CustomException("403", "培训尚未结束，无法进行评分");
        }

        // 3. 检查参与记录是否存在
        VolunteerTrainingParticipation participation = participationMapper.selectByPrimaryKey(volunteerId, trainingId);
        if (participation == null) {
            throw new CustomException("404", "未找到该志愿者的参与记录");
        }

        // 4. 更新评分
        int updatedRows = participationMapper.updateOrgToVolunteerRating(volunteerId, trainingId, rating);
        if (updatedRows == 0) {
            // 此情况理论上较少发生，因为前面已经检查过记录存在
            throw new CustomException("500", "数据库更新评分失败");
        }
    }

}
