USE volunteer_db_test;
GO

PRINT N'--- 开始测试组织机构相关存储过程 ---';
GO

--------------------------------------------------------------------------------
-- 测试 sp_RegisterOrganization (组织机构注册)
--------------------------------------------------------------------------------
PRINT N'--- 测试 sp_RegisterOrganization ---';
-- 1.1 注册一个新组织 (成功)
PRINT N'尝试注册新组织 "爱心测试联盟SP" (用户名为 test_org_user_sp_reg):';
EXEC dbo.sp_RegisterOrganization
    -- @OrgID parameter removed as it's auto-generated by a trigger
    @OrgName = N'爱心测试联盟SP',
    @OrgLoginUserName = N'test_org_user_sp_reg', -- Using a more specific username for this test
    @OrgLoginPassword = N'orgTestPassSP',
    @ContactPersonPhone = '13100001112',
    @ServiceRegion = N'北京朝阳',
    @OrgScale = 55;
GO
-- 期望：返回 0 和 GeneratedOrgID。
-- 验证：
PRINT N'验证组织 "test_org_user_sp_reg" 是否已注册:';
SELECT * FROM dbo.tbl_Organization WHERE OrgLoginUserName = N'test_org_user_sp_reg';
-- 清理
PRINT N'清理测试注册的组织 "test_org_user_sp_reg":';
DELETE FROM dbo.tbl_Organization WHERE OrgLoginUserName = N'test_org_user_sp_reg';
GO

-- 1.2 尝试注册一个已存在的登录用户名 (失败)
PRINT N'尝试注册已存在的登录用户名 "chenxishequ" (来自初始数据):';
EXEC dbo.sp_RegisterOrganization
    @OrgName = N'重复测试社SP',
    @OrgLoginUserName = N'chenxishequ', -- This username exists in initial data
    @OrgLoginPassword = N'anyPassSP',
    @ContactPersonPhone = '13200002223',
    @ServiceRegion = N'上海徐汇',
    @OrgScale = 35;
GO
-- 期望：返回 -1，并提示用户名已存在。

--------------------------------------------------------------------------------
-- 测试 sp_OrganizationLogin (组织机构登录)
--------------------------------------------------------------------------------
PRINT N'--- 测试 sp_OrganizationLogin ---';
-- 2.1a 成功登录 (使用组织登录用户名)
PRINT N'尝试组织 "chenxishequ" 使用正确密码 "orgPassChenxi" 登录 (通过用户名):';
EXEC dbo.sp_OrganizationLogin @OrgIdentifier = N'chenxishequ', @Password = N'orgPassChenxi';
GO

-- 2.1b 成功登录 (使用组织ID - org_001 的登录用户名是 chenxishequ)
PRINT N'尝试组织 "org_001" 使用正确密码 "orgPassChenxi" 登录 (通过组织ID):';
EXEC dbo.sp_OrganizationLogin @OrgIdentifier = 'org_001', @Password = N'orgPassChenxi';
GO

-- 2.2 标识不存在 (使用用户名)
PRINT N'尝试使用不存在的用户名 "non_exist_org_sp" 登录:';
EXEC dbo.sp_OrganizationLogin @OrgIdentifier = N'non_exist_org_sp', @Password = N'anyPassSP';
GO

-- 2.2b 标识不存在 (使用组织ID)
PRINT N'尝试使用不存在的组织ID "org_999_sp" 登录:';
EXEC dbo.sp_OrganizationLogin @OrgIdentifier = 'org_999_sp', @Password = N'anyPassSP';
GO

-- 2.3 密码错误 (使用用户名)
PRINT N'尝试组织 "chenxishequ" 使用错误密码 "wrongPassSP" 登录:';
EXEC dbo.sp_OrganizationLogin @OrgIdentifier = N'chenxishequ', @Password = N'wrongPassSP';
GO

-- 2.3b 密码错误 (使用组织ID)
PRINT N'尝试组织 "org_001" 使用错误密码 "wrongPassSP" 登录:';
EXEC dbo.sp_OrganizationLogin @OrgIdentifier = 'org_001', @Password = N'wrongPassSP';
GO

-- 2.4 账户被冻结
PRINT N'准备测试账户冻结：管理员 "adm_001" 冻结组织 "org_003":';
-- 确保org_003是待认证状态，以便sp_ReviewOrganizationRegistration可以操作
UPDATE dbo.tbl_Organization SET OrgAccountStatus = N'待认证' WHERE OrgID = 'org_003';
EXEC dbo.sp_ReviewOrganizationRegistration @ReviewingAdminID = 'adm_001', @OrgID = 'org_003', @NewStatus = N'冻结';
GO
PRINT N'尝试登录已被冻结的组织 "qihangzhuxue" (用户名对应 org_003):';
EXEC dbo.sp_OrganizationLogin @OrgIdentifier = N'qihangzhuxue', @Password = N'orgPassQihang';
GO
PRINT N'尝试登录已被冻结的组织 (使用ID "org_003"):';
EXEC dbo.sp_OrganizationLogin @OrgIdentifier = 'org_003', @Password = N'orgPassQihang';
GO
-- 清理：将 org_003 状态恢复为 '待认证' (初始数据的状态)
UPDATE dbo.tbl_Organization SET OrgAccountStatus = N'待认证' WHERE OrgID = 'org_003';
GO

--------------------------------------------------------------------------------
-- 测试 sp_UpdateOrganizationProfile (组织更新自己的基本信息)
--------------------------------------------------------------------------------
PRINT N'--- 测试 sp_UpdateOrganizationProfile ---';
GO -- 开始此测试部分的独立批处理

-- 在这个批处理中声明变量
DECLARE @OriginalOrgName_sp3_fix NVARCHAR(20), @OriginalOrgScale_sp3_fix INT;

-- 在同一批处理中捕获原始值
SELECT @OriginalOrgName_sp3_fix = OrgName, @OriginalOrgScale_sp3_fix = OrgScale
FROM dbo.tbl_Organization
WHERE OrgID = 'org_001';

PRINT N'组织 "org_001" 更新前信息 (捕获到的值: 名称=' + ISNULL(@OriginalOrgName_sp3_fix, 'NULL') + ', 规模=' + ISNULL(CONVERT(NVARCHAR(10), @OriginalOrgScale_sp3_fix), 'NULL') + ' ):';
SELECT OrgID, OrgName, ContactPersonPhone, ServiceRegion, OrgScale FROM dbo.tbl_Organization WHERE OrgID = 'org_001';

-- 执行存储过程进行更新
PRINT N'更新组织 "org_001" 的名称和规模:';
EXEC dbo.sp_UpdateOrganizationProfile
    @OrgID = 'org_001',
    @OrgName = N'新晨曦社区服务社SP_Fix', -- 更新后的名称
    @OrgScale = 156; -- 更新后的规模

PRINT N'组织 "org_001" 更新后信息:';
SELECT OrgID, OrgName, ContactPersonPhone, ServiceRegion, OrgScale FROM dbo.tbl_Organization WHERE OrgID = 'org_001';

-- 在同一批处理中使用捕获到的值恢复信息
PRINT N'恢复组织 "org_001" 的原始信息.';
UPDATE dbo.tbl_Organization
SET OrgName = @OriginalOrgName_sp3_fix, OrgScale = @OriginalOrgScale_sp3_fix
WHERE OrgID = 'org_001';

PRINT N'组织 "org_001" 恢复后信息:';
SELECT OrgID, OrgName, ContactPersonPhone, ServiceRegion, OrgScale FROM dbo.tbl_Organization WHERE OrgID = 'org_001';
GO -- sp_UpdateOrganizationProfile 的逻辑测试块结束

-- 测试更新一个不存在的组织 (这可以是一个独立的批处理)
PRINT N'尝试更新不存在的组织 "org_999_sp":';
EXEC dbo.sp_UpdateOrganizationProfile @OrgID = 'org_999_sp', @OrgName = N'不存在的组织SP';
GO



--------------------------------------------------------------------------------
-- 测试 sp_ChangeOrganizationPassword (组织修改自己的登录密码)
--------------------------------------------------------------------------------
PRINT N'--- 测试 sp_ChangeOrganizationPassword ---';
-- org_002, 初始密码 orgPassLvya
PRINT N'组织 "org_002" 尝试修改密码:';
EXEC dbo.sp_ChangeOrganizationPassword @OrgID = 'org_002', @OldPassword = 'orgPassLvya', @NewPassword = 'newOrgPass456SP';
GO
PRINT N'验证组织 "org_002" 新密码登录:';
EXEC dbo.sp_OrganizationLogin @OrgIdentifier = N'lvyahuanbao', @Password = N'newOrgPass456SP';
-- 恢复 org_002 的密码
EXEC dbo.sp_ChangeOrganizationPassword @OrgID = 'org_002', @OldPassword = 'newOrgPass456SP', @NewPassword = 'orgPassLvya';
GO

--------------------------------------------------------------------------------
-- 测试 sp_CreateVolunteerActivityByOrg (组织发布志愿活动)
--------------------------------------------------------------------------------
PRINT N'--- 测试 sp_CreateVolunteerActivityByOrg ---';
PRINT N'组织 "org_001" 发布活动前 ActivityCount (注：此SP不直接更新此计数): ' + ISNULL(CONVERT(VARCHAR(10), (SELECT ActivityCount FROM dbo.tbl_Organization WHERE OrgID = 'org_001')), 'NULL');
GO


-- 5.1 组织 org_001 (已认证) 发布新活动 (成功)
PRINT N'组织 "org_001" 发布新活动 "act_test_create":';
-- 确保删除的是正确的 ActivityID
IF EXISTS (SELECT 1 FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_test_create')
    DELETE FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_test_create';

-- 确保传递的是正确的 ActivityID
EXEC dbo.sp_CreateVolunteerActivityByOrg
    @ActivityID = 'act_test_create',
    @OrgID = 'org_001',
    @ActivityName = N'周末科技馆导览SP-Created',
    @StartTime = '2025-09-01 09:00',
    @EndTime = '2025-09-01 17:00',
    @Location = N'市科技馆SP-Created',
    @RecruitmentCount = 15,
    @ContactPersonPhone = '13811223344';
GO
PRINT N'验证新活动 "act_test_create" 是否已创建:';
SELECT * FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_test_create';
-- 清理
IF EXISTS (SELECT 1 FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_test_create')
    DELETE FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_test_create';
GO

-- 5.2 组织 org_003 (待认证，来自初始数据) 尝试发布活动 (失败)
PRINT N'待认证组织 "org_003" 尝试发布活动 "act_test_fail_sp":';
EXEC dbo.sp_CreateVolunteerActivityByOrg
    @ActivityID = 'act_test_fail_sp',
    @OrgID = 'org_003',
    @ActivityName = N'心灵驿站读书会SP-Fail',
    @StartTime = '2025-09-10 14:00',
    @EndTime = '2025-09-10 16:00',
    @Location = N'启航咖啡厅SP-Fail',
    @RecruitmentCount = 20,
    @ContactPersonPhone = '17702076591';
GO

--------------------------------------------------------------------------------
-- 测试 sp_CreateVolunteerTrainingByOrg (组织发布志愿培训)
--------------------------------------------------------------------------------
PRINT N'--- 测试 sp_CreateVolunteerTrainingByOrg ---';
GO -- GO 语句将下面的 DECLARE 和 PRINT 分隔成不同的批处理，这是允许的

DECLARE @TrainingCount_Org002 VARCHAR(10); -- 声明一个变量来存储转换后的计数值

-- 从数据库中获取 TrainingCount 并转换为 VARCHAR
SELECT @TrainingCount_Org002 = ISNULL(CONVERT(VARCHAR(10), TrainingCount), 'NULL')
FROM dbo.tbl_Organization
WHERE OrgID = 'org_002';

-- 使用变量进行打印
PRINT N'组织 "org_002" 发布培训前 TrainingCount (注：此SP不直接更新此计数): ' + @TrainingCount_Org002;
GO

-- 6.1 组织 org_002 (已认证) 发布新培训 (成功)
PRINT N'组织 "org_002" 发布新培训 "trn_test_create":';
IF EXISTS (SELECT 1 FROM dbo.tbl_VolunteerTraining WHERE TrainingID = 'trn_test_create')
    DELETE FROM dbo.tbl_VolunteerTraining WHERE TrainingID = 'trn_test_create';
EXEC dbo.sp_CreateVolunteerTrainingByOrg
    @TrainingID = 'trn_test_create',
    @OrgID = 'org_002',
    @TrainingName = N'志愿者沟通技巧SP-Created',
    @Theme = N'有效沟通SP-Created',
    @StartTime = '2025-08-15 09:00',
    @EndTime = '2025-08-15 17:00',
    @Location = N'绿芽联盟多功能厅SP-Created',
    @RecruitmentCount = 25,
    @ContactPersonPhone = '13912345678';
GO
PRINT N'验证新培训 "trn_test_create_sp" 是否已创建:';
SELECT * FROM dbo.tbl_VolunteerTraining WHERE TrainingID = 'trn_test_create';
-- 清理
IF EXISTS (SELECT 1 FROM dbo.tbl_VolunteerTraining WHERE TrainingID = 'trn_test_create')
    DELETE FROM dbo.tbl_VolunteerTraining WHERE TrainingID = 'trn_test_create';
GO

--------------------------------------------------------------------------------
-- 测试 sp_OrgReviewVolunteerJoinApplication (组织审核志愿者的加入申请)
--------------------------------------------------------------------------------
PRINT N'--- 测试 sp_OrgReviewVolunteerJoinApplication ---';
-- 初始数据: vol_004 对 org_001 的申请状态为 '申请中'
PRINT N'志愿者 "vol_004" 对组织 "org_001" 的申请状态 (审核前):';
SELECT * FROM dbo.tbl_VolunteerOrganizationJoin WHERE VolunteerID = 'vol_004' AND OrgID = 'org_001';
GO

-- 7.1 组织 org_001 审核通过 vol_004 的加入申请
PRINT N'组织 "org_001" 审核通过 "vol_004" 的加入申请:';
EXEC dbo.sp_OrgReviewVolunteerJoinApplication
    @OperatingOrgID = 'org_001',
    @VolunteerID = 'vol_004',
    @NewStatus = N'已加入';
GO
PRINT N'志愿者 "vol_004" 对组织 "org_001" 的申请状态 (审核后):';
SELECT * FROM dbo.tbl_VolunteerOrganizationJoin WHERE VolunteerID = 'vol_004' AND OrgID = 'org_001';
-- 恢复 vol_004 对 org_001 的申请状态为 '申请中' (初始数据状态)
UPDATE dbo.tbl_VolunteerOrganizationJoin SET MemberStatus = N'申请中' WHERE VolunteerID = 'vol_004' AND OrgID = 'org_001';
GO

-- 7.2 尝试审核一个不存在的申请
PRINT N'组织 "org_001" 尝试审核不存在的志愿者 "vol_999_sp" 的申请:';
EXEC dbo.sp_OrgReviewVolunteerJoinApplication
    @OperatingOrgID = 'org_001',
    @VolunteerID = 'vol_999_sp',
    @NewStatus = N'已加入';
GO

--------------------------------------------------------------------------------
-- 测试 sp_OrgReviewActivityApplication (组织审核志愿者对活动的报名)
--------------------------------------------------------------------------------
PRINT N'--- 测试 sp_OrgReviewActivityApplication ---';
GO -- 开始此测试部分的独立批处理

-- 在这个批处理中声明并初始化变量
DECLARE @InitialAccepted_act002_test8_sp_fix INT, @InitialRecruited_pos003_test8_sp_fix INT;

SELECT @InitialAccepted_act002_test8_sp_fix = AcceptedCount
FROM dbo.tbl_VolunteerActivity
WHERE ActivityID = 'act_002';

SELECT @InitialRecruited_pos003_test8_sp_fix = RecruitedVolunteers
FROM dbo.tbl_Position
WHERE PositionID = 'pos_003' AND ActivityID = 'act_002';

-- 初始数据打印
PRINT N'报名申请 "app_004" 状态 (审核前):';
SELECT ApplicationStatus FROM dbo.tbl_VolunteerActivityApplication WHERE ApplicationID = 'app_004';
PRINT N'活动 act_002 AcceptedCount (前): ' + ISNULL(CONVERT(VARCHAR(10), @InitialAccepted_act002_test8_sp_fix), 'NULL');
PRINT N'岗位 pos_003 RecruitedVolunteers (前): ' + ISNULL(CONVERT(VARCHAR(10), @InitialRecruited_pos003_test8_sp_fix), 'NULL');

-- 执行存储过程
PRINT N'组织 "org_002" 审核通过申请 "app_004" 并分配到岗位 "pos_003":';
EXEC dbo.sp_OrgReviewActivityApplication
    @OperatingOrgID = 'org_002',
    @ApplicationID = 'app_004',
    @NewStatus = N'已通过',
    @ActualPositionID = 'pos_003';

-- 审核后数据打印
PRINT N'报名申请 "app_004" 状态 (审核后):';
SELECT ApplicationStatus FROM dbo.tbl_VolunteerActivityApplication WHERE ApplicationID = 'app_004';
PRINT N'活动 "act_002" 录取人数 (审核后):';
SELECT AcceptedCount FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_002';
PRINT N'岗位 "pos_003" 已招募人数 (审核后):';
SELECT RecruitedVolunteers FROM dbo.tbl_Position WHERE PositionID = 'pos_003';
PRINT N'检查参与记录 for vol_001, act_002, pos_003:';
SELECT * FROM dbo.tbl_VolunteerActivityParticipation WHERE VolunteerID = 'vol_001' AND ActivityID = 'act_002' AND ActualPositionID = 'pos_003';

-- 清理/恢复测试8.1造成的数据变更 (使用之前获取的初始值)
-- 这些 UPDATE 和 DELETE 语句现在与变量声明在同一个批处理中
PRINT N'开始恢复测试数据...';
UPDATE dbo.tbl_VolunteerActivityApplication SET ApplicationStatus = N'待审核' WHERE ApplicationID = 'app_004';
DELETE FROM dbo.tbl_VolunteerActivityParticipation WHERE VolunteerID = 'vol_001' AND ActivityID = 'act_002' AND ActualPositionID = 'pos_003';
UPDATE dbo.tbl_Position SET RecruitedVolunteers = @InitialRecruited_pos003_test8_sp_fix WHERE PositionID = 'pos_003' AND ActivityID = 'act_002';
UPDATE dbo.tbl_VolunteerActivity SET AcceptedCount = @InitialAccepted_act002_test8_sp_fix WHERE ActivityID = 'act_002';
PRINT N'测试数据恢复完毕。';
GO -- 测试 sp_OrgReviewActivityApplication 的逻辑块结束

-- (测试8.2可以放在这里，它是一个新的批处理)
PRINT N'组织 "org_002" 尝试审核申请 "app_001" (属于org_001的活动):';
EXEC dbo.sp_OrgReviewActivityApplication
    @OperatingOrgID = 'org_002',
    @ApplicationID = 'app_001',
    @NewStatus = N'已通过',
    @ActualPositionID = 'pos_001';
G

--------------------------------------------------------------------------------
-- 测试 sp_OrgUpdateVolunteerActivity (组织更新志愿活动信息)
--------------------------------------------------------------------------------
PRINT N'--- 测试 sp_OrgUpdateVolunteerActivity (组织更新志愿活动信息) ---';
GO -- 为此测试部分开始一个新的批处理

-- 在这个批处理中声明并初始化将用于保存原始数据的变量
DECLARE @OriginalActName_sp9_fix NVARCHAR(20),         -- 用于存储原始活动名称
        @OriginalLocation_sp9_fix NVARCHAR(30),      -- 用于存储原始活动地点
        @OriginalRecCount_sp9_fix INT,               -- 用于存储原始招募人数
        @OriginalActStatus_sp9_fix NVARCHAR(10),     -- 用于存储原始活动状态
        @OriginalStartTime_sp9_fix SMALLDATETIME,    -- 用于存储原始开始时间
        @OriginalEndTime_sp9_fix SMALLDATETIME;      -- 用于存储原始结束时间

-- 从数据库表中读取 act_002 活动的当前（原始）信息，并存入上述变量
SELECT @OriginalActName_sp9_fix = ActivityName,
       @OriginalLocation_sp9_fix = Location,
       @OriginalRecCount_sp9_fix = RecruitmentCount,
       @OriginalActStatus_sp9_fix = ActivityStatus,
       @OriginalStartTime_sp9_fix = StartTime,
       @OriginalEndTime_sp9_fix = EndTime
FROM dbo.tbl_VolunteerActivity
WHERE ActivityID = 'act_002';

-- 为了满足测试条件，暂时修改活动 "act_002" 的开始时间、结束时间和状态
-- 确保活动是将来发生的，并且其状态允许被 sp_OrgUpdateVolunteerActivity 存储过程更新
PRINT N'调整活动 "act_002" 的时间和状态以进行测试...';
UPDATE dbo.tbl_VolunteerActivity
SET StartTime = DATEADD(day, 7, GETDATE()),  -- 将开始时间设置为7天后
    EndTime = DATEADD(hour, 3, DATEADD(day, 7, GETDATE())), -- 将结束时间设置为7天后再加上3小时
    ActivityStatus = N'审核通过' -- 假设“审核通过”状态允许被更新
WHERE ActivityID = 'act_002';

PRINT N'活动 "act_002" 更新前的信息 (时间和状态已临时调整):';
SELECT ActivityID, ActivityName, Location, RecruitmentCount, ActivityStatus, StartTime, EndTime
FROM dbo.tbl_VolunteerActivity
WHERE ActivityID = 'act_002';

-- 执行测试目标：组织 org_002 调用存储过程 sp_OrgUpdateVolunteerActivity 更新活动 act_002 的信息
PRINT N'组织 "org_002" 正在更新活动 "act_002" 的信息...';
EXEC dbo.sp_OrgUpdateVolunteerActivity
    @OperatingOrgID = 'org_002',
    @ActivityID = 'act_002',
    @ActivityName = N'大型城市公园清洁日PlusSP_修正版', -- 新的活动名称
    @Location = N'上海市世纪公园NewSP_修正版',     -- 新的活动地点
    @RecruitmentCount = 55;                       -- 新的招募人数

PRINT N'活动 "act_002" 被存储过程更新后的信息 (注意：状态通常会变回“待审核”):';
SELECT ActivityID, ActivityName, Location, RecruitmentCount, ActivityStatus, StartTime, EndTime
FROM dbo.tbl_VolunteerActivity
WHERE ActivityID = 'act_002';

-- 测试完毕后，将活动 "act_002" 的信息恢复到执行测试之前的原始状态
-- 这里会使用本批处理开始时声明并保存了原始值的那些变量
PRINT N'正在恢复活动 "act_002" 的原始信息...';
UPDATE dbo.tbl_VolunteerActivity
SET ActivityName = @OriginalActName_sp9_fix,
    Location = @OriginalLocation_sp9_fix,
    RecruitmentCount = @OriginalRecCount_sp9_fix,
    ActivityStatus = @OriginalActStatus_sp9_fix,
    StartTime = @OriginalStartTime_sp9_fix,
    EndTime = @OriginalEndTime_sp9_fix
WHERE ActivityID = 'act_002';

PRINT N'活动 "act_002" 恢复原始信息后的状态:';
SELECT ActivityID, ActivityName, Location, RecruitmentCount, ActivityStatus, StartTime, EndTime
FROM dbo.tbl_VolunteerActivity
WHERE ActivityID = 'act_002';
GO -- sp_OrgUpdateVolunteerActivity 的逻辑测试块结束

--------------------------------------------------------------------------------
-- 测试 sp_OrgUpdateVolunteerTraining (组织更新志愿培训信息)
--------------------------------------------------------------------------------
PRINT N'--- 测试 sp_OrgUpdateVolunteerTraining ---';
-- 准备一个可更新的培训 trn_update_test_sp (属于 org_001)
IF EXISTS (SELECT 1 FROM dbo.tbl_VolunteerTraining WHERE TrainingID = 'trn_update_test_sp')
    DELETE FROM dbo.tbl_VolunteerTraining WHERE TrainingID = 'trn_update_test_sp';
INSERT INTO dbo.tbl_VolunteerTraining (TrainingID, OrgID, TrainingName, Theme, StartTime, EndTime, Location, RecruitmentCount, TrainingStatus, CreationTime, ContactPersonPhone)
VALUES ('trn_update_test_sp', 'org_001', N'待更新培训SP', N'旧主题SP', DATEADD(day, 8, GETDATE()), DATEADD(hour, 2, DATEADD(day, 8, GETDATE())), N'旧地点SP', 20, N'待审核', GETDATE(), '13111111111');
GO
PRINT N'培训 "trn_update_test_sp" 更新前信息:';
SELECT TrainingID, TrainingName, Theme, Location, TrainingStatus FROM dbo.tbl_VolunteerTraining WHERE TrainingID = 'trn_update_test_sp';
GO

-- 10.1 组织 org_001 更新培训 trn_update_test_sp (成功)
PRINT N'组织 "org_001" 更新培训 "trn_update_test_sp" 信息:';
EXEC dbo.sp_OrgUpdateVolunteerTraining
    @OperatingOrgID = 'org_001',
    @TrainingID = 'trn_update_test_sp',
    @TrainingName = N'已更新培训名称SP',
    @Theme = N'新主题闪亮登场SP';
GO
PRINT N'培训 "trn_update_test_sp" 更新后信息 (状态应仍为待审核):';
SELECT TrainingID, TrainingName, Theme, Location, TrainingStatus FROM dbo.tbl_VolunteerTraining WHERE TrainingID = 'trn_update_test_sp';
-- 清理
IF EXISTS (SELECT 1 FROM dbo.tbl_VolunteerTraining WHERE TrainingID = 'trn_update_test_sp')
    DELETE FROM dbo.tbl_VolunteerTraining WHERE TrainingID = 'trn_update_test_sp';
GO

USE volunteer_db_test; -- 确保在正确的数据库上下文中执行
GO

--------------------------------------------------------------------------------
-- 测试 sp_OrgCancelEvent (组织取消事件 - 活动或培训)
--------------------------------------------------------------------------------
PRINT N'--- 测试 sp_OrgCancelEvent (组织取消事件 - 活动或培训) ---';
GO

-- 测试用例 11.1: 成功取消一个活动
PRINT N'--- 11.1 成功取消一个活动 (act_cncl_001) ---';
-- 清理可能存在的旧数据 (活动报名依赖活动，先删报名)
IF EXISTS (SELECT 1 FROM dbo.tbl_VolunteerActivityApplication WHERE ActivityID = 'act_cncl_001')
    DELETE FROM dbo.tbl_VolunteerActivityApplication WHERE ActivityID = 'act_cncl_001';
IF EXISTS (SELECT 1 FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_cncl_001')
    DELETE FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_cncl_001';

-- 插入测试活动数据 (假设 org_001 已存在且已认证)
INSERT INTO dbo.tbl_VolunteerActivity (
    ActivityID, OrgID, ActivityName, StartTime, EndTime, Location,
    RecruitmentCount, AcceptedCount, ActivityStatus, CreationTime,
    ContactPersonPhone, ActivityDurationHours, IsRatingAggregated -- ActivityRating 可以为 NULL
)
VALUES (
    'act_cncl_001', 'org_001', N'可取消活动01', DATEADD(day, 5, GETDATE()), DATEADD(hour, 3, DATEADD(day, 5, GETDATE())), N'地点A01',
    10, 0, N'审核通过', GETDATE(),
    '13000000001', 3, 'NO'
);

-- 插入关联的报名数据 (假设 vol_001, vol_002 已存在)
INSERT INTO dbo.tbl_VolunteerActivityApplication (ApplicationID, VolunteerID, ActivityID, ApplicationStatus, ApplicationTime)
VALUES ('app_cncl_01a', 'vol_001', 'act_cncl_001', N'已通过', GETDATE());

INSERT INTO dbo.tbl_VolunteerActivityApplication (ApplicationID, VolunteerID, ActivityID, ApplicationStatus, ApplicationTime)
VALUES ('app_cncl_01b', 'vol_002', 'act_cncl_001', N'待审核', GETDATE());
GO

PRINT N'取消前活动 "act_cncl_001" 状态:';
SELECT ActivityStatus FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_cncl_001';
PRINT N'取消前相关报名 "app_cncl_01a" 状态:';
SELECT ApplicationStatus FROM dbo.tbl_VolunteerActivityApplication WHERE ApplicationID = 'app_cncl_01a';
PRINT N'取消前相关报名 "app_cncl_01b" 状态:';
SELECT ApplicationStatus FROM dbo.tbl_VolunteerActivityApplication WHERE ApplicationID = 'app_cncl_01b';
GO

-- 执行取消操作
EXEC dbo.sp_OrgCancelEvent @OperatingOrgID = 'org_001', @EventType = N'Activity', @EventID = 'act_cncl_001';
GO

PRINT N'取消后活动 "act_cncl_001" 状态 (应为 已停用):';
SELECT ActivityStatus FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_cncl_001';
PRINT N'取消后相关报名 "app_cncl_01a" 状态 (应为 取消报名):';
SELECT ApplicationStatus FROM dbo.tbl_VolunteerActivityApplication WHERE ApplicationID = 'app_cncl_01a';
PRINT N'取消后相关报名 "app_cncl_01b" 状态 (应为 取消报名):';
SELECT ApplicationStatus FROM dbo.tbl_VolunteerActivityApplication WHERE ApplicationID = 'app_cncl_01b';
GO

-- 清理测试数据
IF EXISTS (SELECT 1 FROM dbo.tbl_VolunteerActivityApplication WHERE ActivityID = 'act_cncl_001')
    DELETE FROM dbo.tbl_VolunteerActivityApplication WHERE ActivityID = 'act_cncl_001';
IF EXISTS (SELECT 1 FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_cncl_001')
    DELETE FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_cncl_001';
GO

-- 测试用例 11.2: 成功取消一个培训
PRINT N'--- 11.2 成功取消一个培训 (trn_cncl_001) ---';
-- 清理可能存在的旧数据
IF EXISTS (SELECT 1 FROM dbo.tbl_VolunteerTraining WHERE TrainingID = 'trn_cncl_001')
    DELETE FROM dbo.tbl_VolunteerTraining WHERE TrainingID = 'trn_cncl_001';

-- 插入测试培训数据 (假设 org_002 已存在且已认证)
INSERT INTO dbo.tbl_VolunteerTraining (
    TrainingID, OrgID, TrainingName, Theme, StartTime, EndTime, Location,
    RecruitmentCount, TrainingStatus, CreationTime, ContactPersonPhone, IsRatingAggregated -- TrainingRating 可以为 NULL
)
VALUES (
    'trn_cncl_001', 'org_002', N'可取消培训01', N'主题B01', DATEADD(day, 6, GETDATE()), DATEADD(hour, 4, DATEADD(day, 6, GETDATE())), N'地点B01',
    15, N'审核通过', GETDATE(), '13000000002', 'NO'
);
GO

PRINT N'取消前培训 "trn_cncl_001" 状态:';
SELECT TrainingStatus FROM dbo.tbl_VolunteerTraining WHERE TrainingID = 'trn_cncl_001';
GO

-- 执行取消操作
EXEC dbo.sp_OrgCancelEvent @OperatingOrgID = 'org_002', @EventType = N'Training', @EventID = 'trn_cncl_001';
GO

PRINT N'取消后培训 "trn_cncl_001" 状态 (应为 已停用):';
SELECT TrainingStatus FROM dbo.tbl_VolunteerTraining WHERE TrainingID = 'trn_cncl_001';
GO

-- 清理测试数据
IF EXISTS (SELECT 1 FROM dbo.tbl_VolunteerTraining WHERE TrainingID = 'trn_cncl_001')
    DELETE FROM dbo.tbl_VolunteerTraining WHERE TrainingID = 'trn_cncl_001';
GO

-- 测试用例 11.3: 尝试取消不属于本组织的事件
PRINT N'--- 11.3 尝试取消不属于本组织的活动 (act_oth_org01) ---';
-- 清理可能存在的旧数据
IF EXISTS (SELECT 1 FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_oth_org01')
    DELETE FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_oth_org01';

-- 插入测试活动数据，属于 org_001
INSERT INTO dbo.tbl_VolunteerActivity (
    ActivityID, OrgID, ActivityName, StartTime, EndTime, Location,
    RecruitmentCount, ActivityStatus, ContactPersonPhone, ActivityDurationHours
)
VALUES (
    'act_oth_org01', 'org_001', N'他人活动(取消)', DATEADD(day, 5, GETDATE()), DATEADD(hour, 1, DATEADD(day, 5, GETDATE())), N'地点C01',
    5, N'审核通过', '13000000003', 1
);
GO

PRINT N'组织 org_002 尝试取消 org_001 的活动 act_oth_org01 (应失败):';
EXEC dbo.sp_OrgCancelEvent @OperatingOrgID = 'org_002', @EventType = N'Activity', @EventID = 'act_oth_org01';
GO

-- 验证活动状态未改变
PRINT N'尝试取消后，活动 "act_oth_org01" 状态 (应仍为 审核通过):';
SELECT ActivityStatus FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_oth_org01';
GO

-- 清理测试数据
IF EXISTS (SELECT 1 FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_oth_org01')
    DELETE FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_oth_org01';
GO

-- 测试用例 11.4: 尝试取消已开始的活动
PRINT N'--- 11.4 尝试取消已开始的活动 (act_start_01) ---';
-- 清理可能存在的旧数据
IF EXISTS (SELECT 1 FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_start_01')
    DELETE FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_start_01';

-- 插入已开始的测试活动数据
INSERT INTO dbo.tbl_VolunteerActivity (
    ActivityID, OrgID, ActivityName, StartTime, EndTime, Location,
    RecruitmentCount, ActivityStatus, ContactPersonPhone, ActivityDurationHours
)
VALUES (
    'act_start_01', 'org_001', N'已开始活动01', DATEADD(day, -1, GETDATE()), DATEADD(hour, 1, DATEADD(day, -1, GETDATE())), N'地点D01',
    5, N'进行中', '13000000004', 1
);
GO

PRINT N'组织 org_001 尝试取消已开始的活动 act_start_01 (应失败):';
EXEC dbo.sp_OrgCancelEvent @OperatingOrgID = 'org_001', @EventType = N'Activity', @EventID = 'act_start_01';
GO

-- 验证活动状态未改变
PRINT N'尝试取消后，活动 "act_start_01" 状态 (应仍为 进行中):';
SELECT ActivityStatus FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_start_01';
GO

-- 清理测试数据
IF EXISTS (SELECT 1 FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_start_01')
    DELETE FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_start_01';
GO

-- 测试用例 11.5: 使用无效的 EventType
PRINT N'--- 11.5 尝试使用无效的 EventType (应失败) ---';
-- act_001 是来自初始数据的活动，确保它存在以供测试，这里eventType无效才是测试点
EXEC dbo.sp_OrgCancelEvent @OperatingOrgID = 'org_001', @EventType = N'InvalidEvType', @EventID = 'act_001'; -- EventType ID 长度13
GO

-- 测试用例 11.6: 尝试取消不存在的 EventID
PRINT N'--- 11.6 尝试取消不存在的活动ID (act_non_exist) (应失败) ---';
EXEC dbo.sp_OrgCancelEvent @OperatingOrgID = 'org_001', @EventType = N'Activity', @EventID = 'act_non_exist';
GO

PRINT N'--- sp_OrgCancelEvent 测试结束 ---';
GO

--------------------------------------------------------------------------------
-- 测试 sp_OrgRateVolunteerInActivity (组织对参与活动的志愿者进行评分)
--------------------------------------------------------------------------------
PRINT N'--- 测试 sp_OrgRateVolunteerInActivity ---';
GO -- 为此测试部分开始一个新的批处理

-- 初始数据: 活动 act_004 (org_001) 已结束, vol_001 参与 pos_005
-- 假设 act_004, vol_001, pos_005 以及它们之间的参与记录已存在于初始数据中
DECLARE @OriginalOrgToVolRating_act004_sp_fix INT;

-- 将变量的声明和使用放在同一个批处理中
SELECT @OriginalOrgToVolRating_act004_sp_fix = OrgToVolunteerRating
FROM dbo.tbl_VolunteerActivityParticipation
WHERE VolunteerID = 'vol_001' AND ActivityID = 'act_004' AND ActualPositionID = 'pos_005';

PRINT N'对活动 "act_004" 中志愿者 "vol_001" (岗位 "pos_005") 评分前 OrgToVolunteerRating: ' + ISNULL(CONVERT(VARCHAR(10), @OriginalOrgToVolRating_act004_sp_fix), 'NULL');

-- 12.1 组织 org_001 对 vol_001 在 act_004 的表现评分 (成功)
PRINT N'组织 "org_001" 对 "vol_001" 在 "act_004" (岗位 "pos_005") 的表现评9分:';
EXEC dbo.sp_OrgRateVolunteerInActivity
    @OperatingOrgID = 'org_001',
    @VolunteerID = 'vol_001',
    @ActivityID = 'act_004',
    @ActualPositionID = 'pos_005',
    @Rating = 9;

PRINT N'对活动 "act_004" 中志愿者 "vol_001" (岗位 "pos_005") 评分后 OrgToVolunteerRating:';
SELECT OrgToVolunteerRating
FROM dbo.tbl_VolunteerActivityParticipation
WHERE VolunteerID = 'vol_001' AND ActivityID = 'act_004' AND ActualPositionID = 'pos_005';

-- 恢复评分
PRINT N'恢复 "act_004" 中 "vol_001" (岗位 "pos_005") 的原始评分...';
UPDATE dbo.tbl_VolunteerActivityParticipation
SET OrgToVolunteerRating = @OriginalOrgToVolRating_act004_sp_fix
WHERE VolunteerID = 'vol_001' AND ActivityID = 'act_004' AND ActualPositionID = 'pos_005';
GO -- 结束测试 12.1 的批处理

-- 12.2 尝试对未结束的活动评分 (失败)
-- 初始数据: 活动 act_001 (org_001) 是 '进行中'
-- 假设 act_001, vol_001, pos_001 以及它们之间的参与记录已存在于初始数据中，且 act_001 是进行中
PRINT N'组织 "org_001" 尝试对进行中的活动 "act_001" 的志愿者 "vol_001" (岗位 pos_001) 评分 (应失败):';
EXEC dbo.sp_OrgRateVolunteerInActivity
    @OperatingOrgID = 'org_001',
    @VolunteerID = 'vol_001',
    @ActivityID = 'act_001',
    @ActualPositionID = 'pos_001',
    @Rating = 8;
GO

--------------------------------------------------------------------------------
-- 测试 sp_OrgRateVolunteerInTraining (组织对参与培训的志愿者进行评分)
--------------------------------------------------------------------------------
PRINT N'--- 测试 sp_OrgRateVolunteerInTraining ---';
GO -- 为此测试部分开始一个新的批处理

-- 初始数据: 培训 trn_002 (org_002) 是 '已结束', vol_002 参与
-- 假设 trn_002, vol_002 以及它们之间的参与记录已存在于初始数据中
DECLARE @OriginalOrgToVolRating_trn002_sp_fix INT;

-- 将变量的声明和使用放在同一个批处理中
SELECT @OriginalOrgToVolRating_trn002_sp_fix = OrgToVolunteerRating
FROM dbo.tbl_VolunteerTrainingParticipation
WHERE VolunteerID = 'vol_002' AND TrainingID = 'trn_002';

PRINT N'对培训 "trn_002" 中志愿者 "vol_002" 评分前 OrgToVolunteerRating: ' + ISNULL(CONVERT(VARCHAR(10), @OriginalOrgToVolRating_trn002_sp_fix), 'NULL');

-- 13.1 组织 org_002 对 vol_002 在 trn_002 的表现评分 (成功)
PRINT N'组织 "org_002" 对 "vol_002" 在 "trn_002" 的表现评7分:';
EXEC dbo.sp_OrgRateVolunteerInTraining
    @OperatingOrgID = 'org_002',
    @VolunteerID = 'vol_002',
    @TrainingID = 'trn_002',
    @Rating = 7;

PRINT N'对培训 "trn_002" 中志愿者 "vol_002" 评分后 OrgToVolunteerRating:';
SELECT OrgToVolunteerRating
FROM dbo.tbl_VolunteerTrainingParticipation
WHERE VolunteerID = 'vol_002' AND TrainingID = 'trn_002';

-- 恢复评分
PRINT N'恢复 "trn_002" 中 "vol_002" 的原始评分...';
UPDATE dbo.tbl_VolunteerTrainingParticipation
SET OrgToVolunteerRating = @OriginalOrgToVolRating_trn002_sp_fix
WHERE VolunteerID = 'vol_002' AND TrainingID = 'trn_002';
GO -- 结束测试 13.1 的批处理

--------------------------------------------------------------------------------
-- 测试 sp_AddEventTimeslot
--------------------------------------------------------------------------------
PRINT N'--- 开始测试 sp_AddEventTimeslot 存储过程 ---';
GO
-- 初始数据: 活动 'act_001'(org_001), 培训 'trn_001'(org_001)
-- 假设 act_001, trn_001 已存在于初始数据中

-- 14.1 成功为活动 'act_001' 添加一个新时段
PRINT N'14.1 成功为活动 "act_001" 添加新时段 "ts_act01_001":';
IF EXISTS (SELECT 1 FROM dbo.tbl_ActivityTimeslot WHERE TimeslotID = 'ts_act01_001')
    DELETE FROM dbo.tbl_ActivityTimeslot WHERE TimeslotID = 'ts_act01_001';
EXEC dbo.sp_AddEventTimeslot @TimeslotID = 'ts_act01_001', @EventID = 'act_001', @StartTime = '2025-06-10 13:00', @EndTime = '2025-06-10 14:00', @OperatingOrgID = 'org_001';
GO
PRINT N'验证时段 "ts_act01_001" 是否已添加:';
SELECT * FROM dbo.tbl_ActivityTimeslot WHERE TimeslotID = 'ts_act01_001';
GO

-- 14.2 成功为培训 'trn_001' 添加一个新时段 (不提供操作组织ID)
PRINT N'14.2 成功为培训 "trn_001" 添加新时段 "ts_trn01_001":';
IF EXISTS (SELECT 1 FROM dbo.tbl_ActivityTimeslot WHERE TimeslotID = 'ts_trn01_001')
    DELETE FROM dbo.tbl_ActivityTimeslot WHERE TimeslotID = 'ts_trn01_001';
EXEC dbo.sp_AddEventTimeslot @TimeslotID = 'ts_trn01_001', @EventID = 'trn_001', @StartTime = '2025-06-20 18:00', @EndTime = '2025-06-20 19:00';
GO
PRINT N'验证时段 "ts_trn01_001" 是否已添加:';
SELECT * FROM dbo.tbl_ActivityTimeslot WHERE TimeslotID = 'ts_trn01_001';
GO

-- 14.3 尝试添加一个已存在的 TimeslotID (失败)
-- 假设 tslot_001 是来自初始数据的，或者在此测试前由其他方式创建
PRINT N'14.3 尝试添加已存在的时段ID "tslot_001" (来自初始数据，或手动创建以测试):';
-- 为了确保此测试的可重复性，我们先尝试插入一个名为 tslot_001 的记录
IF NOT EXISTS (SELECT 1 FROM dbo.tbl_ActivityTimeslot WHERE TimeslotID = 'tslot_001')
BEGIN
    -- 假设 act_001 存在
    INSERT INTO dbo.tbl_ActivityTimeslot (TimeslotID, EventID, StartTime, EndTime)
    VALUES ('tslot_001', 'act_001', '2025-01-01 09:00', '2025-01-01 10:00');
END
EXEC dbo.sp_AddEventTimeslot @TimeslotID = 'tslot_001', @EventID = 'act_001', @StartTime = '2025-06-11 09:00', @EndTime = '2025-06-11 10:00';
GO

-- 14.4 尝试为无效的 EventID 添加时段 (失败)
PRINT N'14.4 尝试为不存在的事件ID "evt_invalid01" 添加时段:';
EXEC dbo.sp_AddEventTimeslot @TimeslotID = 'ts_invalid_01', @EventID = 'evt_invalid01', @StartTime = '2025-06-12 09:00', @EndTime = '2025-06-12 10:00';
GO

-- 14.5 尝试添加开始时间晚于或等于结束时间的时段 (失败)
PRINT N'14.5.1 尝试添加开始时间等于结束时间的时段:';
EXEC dbo.sp_AddEventTimeslot @TimeslotID = 'ts_time_err_a', @EventID = 'act_001', @StartTime = '2025-06-13 10:00', @EndTime = '2025-06-13 10:00';
GO
PRINT N'14.5.2 尝试添加开始时间晚于结束时间的时段:';
EXEC dbo.sp_AddEventTimeslot @TimeslotID = 'ts_time_err_b', @EventID = 'act_001', @StartTime = '2025-06-13 11:00', @EndTime = '2025-06-13 10:00';
GO

-- 14.6 (可选权限校验) 尝试由非所属组织为事件添加时段 (失败)
PRINT N'14.6 组织 "org_002" 尝试为不属于自己的活动 "act_001" (属于org_001) 添加时段:';
EXEC dbo.sp_AddEventTimeslot @TimeslotID = 'ts_auth_err01', @EventID = 'act_001', @StartTime = '2025-06-14 09:00', @EndTime = '2025-06-14 10:00', @OperatingOrgID = 'org_002';
GO

-- 清理本节测试中创建的时段 (只清理明确由本测试脚本创建的)
DELETE FROM dbo.tbl_ActivityTimeslot WHERE TimeslotID IN (
    'ts_act01_001', 'ts_trn01_001',
    'ts_invalid_01',         -- 尽管可能因SP错误未创建
    'ts_time_err_a',         -- 尽管可能因SP错误未创建
    'ts_time_err_b',         -- 尽管可能因SP错误未创建
    'ts_auth_err01',         -- 尽管可能因SP错误未创建
    'tslot_001'              -- 清理为测试 14.3 而可能插入的 tslot_001
) AND EventID IN ('act_001', 'trn_001', 'evt_invalid01'); -- 添加 EventID 条件以更精确删除
GO

PRINT N'--- sp_AddEventTimeslot 存储过程测试结束 ---';
GO

USE volunteer_db_test;
GO

PRINT N'--- 开始测试组织综合评分计算相关存储过程 (OrgID手动指定) ---';
GO

--------------------------------------------------------------------------------
-- 准备阶段：插入测试数据
--------------------------------------------------------------------------------
PRINT N'--- 阶段0: 准备测试数据 ---';
GO

-- 在这个批处理中声明、清理、插入并使用变量
DECLARE @TestOrgID1 CHAR(15) = 'ORG_RATE_TST01'; -- 14 chars
DECLARE @TestOrgID2 CHAR(15) = 'ORG_RATE_TST02'; -- 14 chars

-- 清理可能存在的同名测试组织 (通过OrgID和OrgLoginUserName确保清理干净)
PRINT N'清理旧的测试组织（如果存在）...';
IF EXISTS (SELECT 1 FROM dbo.tbl_Organization WHERE OrgID = @TestOrgID1 OR OrgLoginUserName = 'org_rating_test1_usr')
    DELETE FROM dbo.tbl_Organization WHERE OrgID = @TestOrgID1 OR OrgLoginUserName = 'org_rating_test1_usr';
IF EXISTS (SELECT 1 FROM dbo.tbl_Organization WHERE OrgID = @TestOrgID2 OR OrgLoginUserName = 'org_rating_test2_usr')
    DELETE FROM dbo.tbl_Organization WHERE OrgID = @TestOrgID2 OR OrgLoginUserName = 'org_rating_test2_usr';

-- 插入测试组织 (显式插入OrgID)
PRINT N'插入测试组织...';
INSERT INTO dbo.tbl_Organization (OrgID, OrgName, OrgLoginUserName, OrgLoginPassword, ContactPersonPhone, ServiceRegion, OrgScale, OrgAccountStatus, ActivityCount, TrainingCount, TotalServiceHours, OrgRating)
VALUES (@TestOrgID1, N'评分测试组织一', 'org_rating_test1_usr', 'pass1', '13000000011', '北京', 50, N'已认证', 0, 0, 0, 1.0); -- 初始统计数据设为0，由后续步骤明确设置
INSERT INTO dbo.tbl_Organization (OrgID, OrgName, OrgLoginUserName, OrgLoginPassword, ContactPersonPhone, ServiceRegion, OrgScale, OrgAccountStatus, OrgRating)
VALUES (@TestOrgID2, N'评分测试组织二', 'org_rating_test2_usr', 'pass2', '13000000022', '上海', 30, N'已认证', 1.0); -- 初始统计数据默认为0

PRINT N'测试组织ID1: ' + @TestOrgID1;
PRINT N'测试组织ID2: ' + @TestOrgID2;

-- 清理可能存在的旧测试活动/培训及其关联数据
PRINT N'清理旧的测试活动、培训及关联数据...';
DELETE FROM dbo.tbl_VolunteerActivityParticipation WHERE ActivityID IN ('act_rate_tst01', 'act_rate_tst02', 'act_rate_tst03');
DELETE FROM dbo.tbl_Position WHERE PositionID IN ('pos_act01_p1', 'pos_act01_p2', 'pos_act02_p1'); -- 确保清理测试岗位
DELETE FROM dbo.tbl_VolunteerActivity WHERE ActivityID IN ('act_rate_tst01', 'act_rate_tst02', 'act_rate_tst03');
DELETE FROM dbo.tbl_VolunteerTrainingParticipation WHERE TrainingID IN ('trn_rate_tst01', 'trn_rate_tst02');
DELETE FROM dbo.tbl_VolunteerTraining WHERE TrainingID IN ('trn_rate_tst01', 'trn_rate_tst02');

-- 插入测试活动数据 (为组织 @TestOrgID1)
PRINT N'插入测试活动数据...';
INSERT INTO dbo.tbl_VolunteerActivity (ActivityID, OrgID, ActivityName, StartTime, EndTime, Location, RecruitmentCount, ActivityStatus, ContactPersonPhone, ActivityDurationHours, IsRatingAggregated, ActivityRating)
VALUES ('act_rate_tst01', @TestOrgID1, N'评分活动01', DATEADD(day, -10, GETDATE()), DATEADD(day, -9, GETDATE()), N'地点X', 10, N'已结束', '13100000001', 5, 'NO', NULL);
INSERT INTO dbo.tbl_VolunteerActivity (ActivityID, OrgID, ActivityName, StartTime, EndTime, Location, RecruitmentCount, ActivityStatus, ContactPersonPhone, ActivityDurationHours, IsRatingAggregated, ActivityRating)
VALUES ('act_rate_tst02', @TestOrgID1, N'评分活动02', DATEADD(day, -15, GETDATE()), DATEADD(day, -14, GETDATE()), N'地点Y', 5, N'已结束', '13100000002', 3, 'NO', NULL);
INSERT INTO dbo.tbl_VolunteerActivity (ActivityID, OrgID, ActivityName, StartTime, EndTime, Location, RecruitmentCount, ActivityStatus, ContactPersonPhone, ActivityDurationHours, IsRatingAggregated, ActivityRating)
VALUES ('act_rate_tst03', @TestOrgID1, N'评分活动03 (无评分)', DATEADD(day, -20, GETDATE()), DATEADD(day, -19, GETDATE()), N'地点Z', 8, N'已结束', '13100000003', 2, 'NO', NULL);

-- 插入测试岗位数据
PRINT N'插入测试岗位数据...';
IF NOT EXISTS (SELECT 1 FROM dbo.tbl_Position WHERE PositionID = 'pos_act01_p1')
    INSERT INTO dbo.tbl_Position (PositionID, PositionName, ActivityID, PositionServiceHours, RequiredVolunteers, RecruitedVolunteers) VALUES ('pos_act01_p1', '测试岗位A1P1', 'act_rate_tst01', 2, 5, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.tbl_Position WHERE PositionID = 'pos_act01_p2')
    INSERT INTO dbo.tbl_Position (PositionID, PositionName, ActivityID, PositionServiceHours, RequiredVolunteers, RecruitedVolunteers) VALUES ('pos_act01_p2', '测试岗位A1P2', 'act_rate_tst01', 2, 5, 0);
IF NOT EXISTS (SELECT 1 FROM dbo.tbl_Position WHERE PositionID = 'pos_act02_p1')
    INSERT INTO dbo.tbl_Position (PositionID, PositionName, ActivityID, PositionServiceHours, RequiredVolunteers, RecruitedVolunteers) VALUES ('pos_act02_p1', '测试岗位A2P1', 'act_rate_tst02', 2, 3, 0);

-- 插入测试活动参与和评分数据 (假设志愿者 vol_001, vol_002, vol_003 已存在)
PRINT N'插入测试活动参与数据...';
INSERT INTO dbo.tbl_VolunteerActivityParticipation (VolunteerID, ActivityID, ActualPositionID, VolunteerToOrgRating, IsCheckedIn)
VALUES ('vol_001', 'act_rate_tst01', 'pos_act01_p1', 8, N'是'), ('vol_002', 'act_rate_tst01', 'pos_act01_p2', 10, N'是'); -- 活动1评分
INSERT INTO dbo.tbl_VolunteerActivityParticipation (VolunteerID, ActivityID, ActualPositionID, VolunteerToOrgRating, IsCheckedIn)
VALUES ('vol_003', 'act_rate_tst02', 'pos_act02_p1', 6, N'是'); -- 活动2评分

-- 插入测试培训数据 (为组织 @TestOrgID2)
PRINT N'插入测试培训数据...';
INSERT INTO dbo.tbl_VolunteerTraining (TrainingID, OrgID, TrainingName, Theme, StartTime, EndTime, Location, RecruitmentCount, TrainingStatus, ContactPersonPhone, IsRatingAggregated, TrainingRating)
VALUES ('trn_rate_tst01', @TestOrgID2, N'评分培训01', N'沟通技巧', DATEADD(day, -12, GETDATE()), DATEADD(day, -11, GETDATE()), N'会议室A', 20, N'已结束', '13200000001', 'NO', NULL);
INSERT INTO dbo.tbl_VolunteerTraining (TrainingID, OrgID, TrainingName, Theme, StartTime, EndTime, Location, RecruitmentCount, TrainingStatus, ContactPersonPhone, IsRatingAggregated, TrainingRating)
VALUES ('trn_rate_tst02', @TestOrgID2, N'评分培训02 (无评分)', N'应急处理', DATEADD(day, -18, GETDATE()), DATEADD(day, -17, GETDATE()), N'会议室B', 15, N'已结束', '13200000002', 'NO', NULL);

-- 插入测试培训参与和评分数据 (假设志愿者 vol_001, vol_004 已存在)
PRINT N'插入测试培训参与数据...';
INSERT INTO dbo.tbl_VolunteerTrainingParticipation (VolunteerID, TrainingID, VolunteerToOrgRating, IsCheckedIn)
VALUES ('vol_001', 'trn_rate_tst01', 9, N'是'), ('vol_004', 'trn_rate_tst01', 7, N'是'); -- 培训1评分
GO -- 结束准备数据的大批处理

--------------------------------------------------------------------------------
-- 阶段一测试：sp_finalize_event_average_scores
--------------------------------------------------------------------------------
PRINT N'--- 阶段一测试: 执行 sp_finalize_event_average_scores ---';
EXEC dbo.sp_finalize_event_average_scores;
GO

PRINT N'--- 验证阶段一结果 ---';
-- 活动1 (act_rate_tst01) 应该有平均分 (8+10)/2 = 9.0 -> 存入INT后为9
SELECT ActivityID, ActivityRating, IsRatingAggregated FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_rate_tst01' AND OrgID = 'ORG_RATE_TST01';
-- 活动2 (act_rate_tst02) 应该有平均分 6.0 -> 存入INT后为6
SELECT ActivityID, ActivityRating, IsRatingAggregated FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_rate_tst02' AND OrgID = 'ORG_RATE_TST01';
-- 活动3 (act_rate_tst03) 应该没有评分 (NULL)，但 IsRatingAggregated 应为 YES
SELECT ActivityID, ActivityRating, IsRatingAggregated FROM dbo.tbl_VolunteerActivity WHERE ActivityID = 'act_rate_tst03' AND OrgID = 'ORG_RATE_TST01';

-- 培训1 (trn_rate_tst01) 应该有平均分 (9+7)/2 = 8.0 -> 存入INT后为8
SELECT TrainingID, TrainingRating, IsRatingAggregated FROM dbo.tbl_VolunteerTraining WHERE TrainingID = 'trn_rate_tst01' AND OrgID = 'ORG_RATE_TST02';
-- 培训2 (trn_rate_tst02) 应该没有评分 (NULL)，但 IsRatingAggregated 应为 YES
SELECT TrainingID, TrainingRating, IsRatingAggregated FROM dbo.tbl_VolunteerTraining WHERE TrainingID = 'trn_rate_tst02' AND OrgID = 'ORG_RATE_TST02';
GO

--------------------------------------------------------------------------------
-- 为阶段二准备：更新组织统计数据
--------------------------------------------------------------------------------
PRINT N'--- 为阶段二准备组织统计数据 ---';
DECLARE @TestOrgID1_Prep CHAR(15) = 'ORG_RATE_TST01';
DECLARE @TestOrgID2_Prep CHAR(15) = 'ORG_RATE_TST02';

UPDATE dbo.tbl_Organization
SET ActivityCount = 3, -- 3个测试活动
    TrainingCount = 0, -- 组织1没有创建测试培训
    TotalServiceHours = (5+3+2) -- 活动01(5h) + 活动02(3h) + 活动03(2h) = 10h
WHERE OrgID = @TestOrgID1_Prep;

UPDATE dbo.tbl_Organization
SET ActivityCount = 0, -- 组织2没有创建测试活动
    TrainingCount = 2, -- 2个测试培训
    TotalServiceHours = 0 -- 培训时长不计入组织总服务时长
WHERE OrgID = @TestOrgID2_Prep;
GO


--------------------------------------------------------------------------------
-- 阶段二测试：sp_calculate_organization_overall_ratings
--------------------------------------------------------------------------------
PRINT N'--- 阶段二测试: 执行 sp_calculate_organization_overall_ratings (已修正版) ---';
-- 确保使用的是修正后的 sp_calculate_organization_overall_ratings 存储过程
-- (即包含显式CAST和调试PRINT语句，并且PRINT中的子查询已修正的版本)
EXEC dbo.sp_calculate_organization_overall_ratings;
GO

PRINT N'--- 验证阶段二结果 ---';
DECLARE @TestOrgID1_Verify CHAR(15) = 'ORG_RATE_TST01';
DECLARE @TestOrgID2_Verify CHAR(15) = 'ORG_RATE_TST02';

-- 验证组织 @TestOrgID1_Verify 的评分
PRINT N'验证组织 ' + @TestOrgID1_Verify;
-- 预期计算（基于修正后的 sp_calculate_organization_overall_ratings，其中 AVG(CAST(... AS DECIMAL)) 会得到7.5）：
-- Org1 Score_AvgActivityRating = 7.5
-- Org1 Score_AvgTrainingRating = 1.0 (默认)
-- Org1 Score_ActivityCount = 4.0 (ActivityCount = 3)
-- Org1 Score_TrainingCount = 1.0 (TrainingCount = 0)
-- Org1 Score_TotalServiceHours = 1.0 (TotalServiceHours = 10)
-- FinalOrgRating = (7.5*0.3) + (1.0*0.2) + (4.0*0.2) + (1.0*0.1) + (1.0*0.2)
--                = 2.25 + 0.2 + 0.8 + 0.1 + 0.2 = 3.55. 四舍五入后为 3.6
SELECT OrgID, OrgName, OrgRating, ActivityCount, TrainingCount, TotalServiceHours FROM dbo.tbl_Organization WHERE OrgID = @TestOrgID1_Verify;

-- 验证组织 @TestOrgID2_Verify 的评分
PRINT N'验证组织 ' + @TestOrgID2_Verify;
-- 预期计算（基于修正后的 sp_calculate_organization_overall_ratings，其中 AVG(CAST(... AS DECIMAL)) 会得到8.0）：
-- Org2 Score_AvgActivityRating = 1.0 (默认)
-- Org2 Score_AvgTrainingRating = 8.0
-- Org2 Score_ActivityCount = 1.0 (ActivityCount = 0)
-- Org2 Score_TrainingCount = 6.0 (TrainingCount = 2)
-- Org2 Score_TotalServiceHours = 1.0 (TotalServiceHours = 0)
-- FinalOrgRating = (1.0*0.3) + (8.0*0.2) + (1.0*0.2) + (6.0*0.1) + (1.0*0.2)
--                = 0.3 + 1.6 + 0.2 + 0.6 + 0.2 = 2.9
SELECT OrgID, OrgName, OrgRating, ActivityCount, TrainingCount, TotalServiceHours FROM dbo.tbl_Organization WHERE OrgID = @TestOrgID2_Verify;
GO

--------------------------------------------------------------------------------
-- 清理阶段：删除测试数据
--------------------------------------------------------------------------------
PRINT N'--- 清理测试数据 ---';
-- 先删除依赖表中的数据
DELETE FROM dbo.tbl_VolunteerActivityParticipation WHERE ActivityID IN ('act_rate_tst01', 'act_rate_tst02', 'act_rate_tst03');
DELETE FROM dbo.tbl_Position WHERE PositionID IN ('pos_act01_p1', 'pos_act01_p2', 'pos_act02_p1');
DELETE FROM dbo.tbl_VolunteerActivity WHERE ActivityID IN ('act_rate_tst01', 'act_rate_tst02', 'act_rate_tst03');

DELETE FROM dbo.tbl_VolunteerTrainingParticipation WHERE TrainingID IN ('trn_rate_tst01', 'trn_rate_tst02');
DELETE FROM dbo.tbl_VolunteerTraining WHERE TrainingID IN ('trn_rate_tst01', 'trn_rate_tst02');

-- 最后删除组织
DECLARE @TestOrgID1_Clean CHAR(15) = 'ORG_RATE_TST01';
DECLARE @TestOrgID2_Clean CHAR(15) = 'ORG_RATE_TST02';

IF EXISTS (SELECT 1 FROM dbo.tbl_Organization WHERE OrgID = @TestOrgID1_Clean)
    DELETE FROM dbo.tbl_Organization WHERE OrgID = @TestOrgID1_Clean;
IF EXISTS (SELECT 1 FROM dbo.tbl_Organization WHERE OrgID = @TestOrgID2_Clean)
    DELETE FROM dbo.tbl_Organization WHERE OrgID = @TestOrgID2_Clean;
GO

PRINT N'--- 组织综合评分计算相关存储过程测试结束 ---';
GO

PRINT N'--- 组织机构相关存储过程测试全部结束 ---';
GO